name       : haskell-hashtables
version    : 1.2.3.4
release    : 3
source     :
    - https://hackage.haskell.org/package/hashtables-1.2.3.4/hashtables-1.2.3.4.tar.gz : 125ce62701fba3f666609f5c75f452005aa5d32dff4eeee3f3903c30b2ed55e6
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides a couple of different implementations of mutable hash tables in the ST monad, as well as a typeclass abstracting their common operations, and a set of wrappers to use the hash tables in the IO monad.
description: |
    This package provides a couple of different implementations of mutable hash tables in the ST monad, as well as a typeclass abstracting their common operations, and a set of wrappers to use the hash tables in the IO monad.
builddeps  :
    - haskell-cabal-install
    - haskell-hashable-devel
    - haskell-vector-devel
rundeps    :
    - devel:
        - haskell-hashable-devel
        - haskell-vector-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
