name       : haskell-hashtables
version    : 1.2.1.1
release    : 1
source     :
    - http://hackage.haskell.org/package/hashtables-1.2.1.1/hashtables-1.2.1.1.tar.gz : 227f554a93310645c654254659969b347de3d1bf3d98901dbb5c113ece72e951
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides a couple of different implementations of mutable hash tables in the ST monad, as well as a typeclass abstracting their common operations, and a set of wrappers to use the hash tables in the IO monad.
description: |
    This package provides a couple of different implementations of mutable hash tables in the ST monad, as well as a typeclass abstracting their common operations, and a set of wrappers to use the hash tables in the IO monad.
builddeps  :
    - haskell-cabal-install
    - haskell-vector
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
