name       : haskell-hashtables
version    : 1.2.3.0
release    : 2
source     :
    - https://hackage.haskell.org/package/hashtables-1.2.3.0/hashtables-1.2.3.0.tar.gz : f956b4bb6113f30193c9d85caebeda5000c29d8acf4f4994af650d3748bf73a5
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides a couple of different implementations of mutable hash tables in the ST monad, as well as a typeclass abstracting their common operations, and a set of wrappers to use
    the hash tables in the IO monad.
description: |
    This package provides a couple of different implementations of mutable hash tables in the ST monad, as well as a typeclass abstracting their common operations, and a set of wrappers to use the hash tables in the IO monad.
builddeps  :
    - haskell-cabal-install
    - haskell-hashable
    - haskell-vector
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
